comparation = {
    # currency_list 
    1 : [
        'USD $',
        'UYU $',
        'ARS $',
        'BRL R$',
        'MXN $',
        'GPB €',
        'EUR £',
        'RUB ₽',
        'BTC ₿',
        'BNB',
        'ETH Ξ'
    ],
    # value_list
    2 : [
        'bananas',
        'naranjas',
        'mandarinas',
        'sandias',
        'lechugas',
        'peras',
        'bananas negras',
        'manzanas podridas',
        'manzanas rojas',
        'manzanas verdes',
        'manzanas amarillas',
        'autos usados',
        'autos nuevos',
        'huevos',
        'botellas de agua',
        'desmorrugadores',
        'pipas de agua',
        'hoteles 5 estrellas',
        'CORTASTES TODA LA LOOZes',
        'viajes en el tiempo',
        'Lunes de mañana',
        'Viernes de noche',
        'Fernets con Coca',
        'Playlist de el Doctor en #Ñeri-Lounge',
        'chasquis',
        'Bryans',
        'minutas del BCU',
        'Fideos',
        'Tirabuzones',
        'Mostacholes',
        'tallarines',
        'ñoquis',
        'pastas italianas',
        'NIERIBOTS'
    ],
    # random phrases
    3 : [
        'Un ñeri vale lo que la com unidad desea que valga! -Theneydoc',
        'El valor del ñeri son los amigos que hiciste en el camino',
        'Lo que te diga tu corazon',
        'Ella ya no te quiere',
        'A veces hace bien bañarse',
        'Alto guiso',
        'infinito. Sí, infinito, cada ñeri vale infinito #BAM',
        'vos vales más',
        'Qué es el valor realmente?',
        'Se cayó la base de datos, consultá de nuevo en unas décadas',
        '1.000.000 de ñeris',
        'ni pa comprar fideos xd',
        '0,000000001 ñermes',
        'Mucho mejor que el URUBIT'
    ]
}